---
title: "Gov 50 Final Project"
author: "Marcela Castillo Mejia"
description: "My final project"
output:
  distill::distill_article:
    self_contained: false
---


## Milestone 1

I am keen to investigate data concerning Nicaraguan migration post-2018. Following the 2018 protests and the student movement, approximately 700,000 Nicaraguan citizens emigrated between 2018 and 2023, with the majority relocating to Costa Rica, the United States, and Spain. If I secure the data for this research endeavor, my objective will be to analyze the various migration trends of Nicaraguans since 2018. The ultimate aim is to discern the demographics (age, economic status, and ethnicity) most impacted by this migration and to ascertain which nations have been most welcoming to Nicaraguan migrants. 

## Milestone 2

In this study, I plan to examine the correlation between the 2018 socio-political crisis in Nicaragua and the subsequent trends in asylum filings and decisions in the U.S. I hypothesize that the surge in authoritarianism and the socio-political unrest in Nicaragua during and following 2018 triggered an increase in both the number of Nicaraguans seeking asylum and the number of asylum decisions by U.S. authorities.
My sample is comprised of immigration data spanning from the year 2003 to 2023, capturing a broad timeframe that allows for analysis of trends before, during, and after the 2018 crisis. My units of analysis are individual years (2000:2023).
The primary explanatory variable of interest is the occurrence of the socio-political crisis, which is primarily centered around the year 2018. This variable is coded =1 for years during and after the crisis (2018-2023) and =0 for years before the crisis (2003-2017).  
My first outcome variable is the count of asylum filings by Nicaraguans in the U.S. in a given year. An increase in this number in years coded as 1 would be indicative of a correlation with the crisis. My second outcome variable is the count of asylum decisions by U.S. authorities for Nicaraguan nationals, which includes both approvals and denials. A significant uptick in these numbers during and after 2018 would also support my hypothesis.
These variables are measured using the official data from TRAC and other relevant immigration authorities, ensuring accuracy and comprehensiveness in the counts.
If I observe a marked increase in both asylum filings and decisions corresponding with the timing of the socio-political crisis in Nicaragua, this would provide strong support for my hypothesis. Conversely, if I observe no change or a decrease in these numbers in the period of interest, this would argue against my hypothesis.
In my regression analysis, positive, significant coefficients on the crisis indicator variable for both outcome variables would indicate support for my hypothesis, showing that the 2018 socio-political crisis in Nicaragua is associated with increased asylum filings and decisions in the U.S. 

##Milestone 3

```{r}
#downloading packages
library(ggplot2)
library(dplyr)
library(tidyverse)
library(tidyr)
#Downloading data
nicaragua_asylum_filings <- read.csv("Nicaragua Asylum Filings.csv")
nicaragua_asylum_decisions <- read.csv("Nicaragua Asylum Decisions copy.csv")

library(tidyr)
library(ggplot2)


colnames(nicaragua_asylum_filings)

nicaragua_filings <- nicaragua_asylum_filings |>
  filter(Filing == "State") |>
  gather(key = "Year", value = "Filings", "X2001":"X2023") |>
  filter(!is.na(Filings))
ggplot(data = nicaragua_filings, aes(x = as.numeric(Year), y = as.numeric(Filings))) + geom_line((aes(group = 1))) + geom_point() + 
  labs(title = "Total Asylum Filings Over the Years",
       x = "Year", 
       y = "Number of Filings") +
  theme_minimal()
  

library(tidyr)
library(ggplot2)

colnames(nicaragua_asylum_filings)

library(tidyr)
library(ggplot2)

# Filter for the 'All' row and select the columns from 2001 to 2023
long_data <- nicaragua_asylum_filings |>
  filter(Filing == "All") |>
  select("X2001":"X2023") |>
  gather(key = "Year", value = "X2021:X2023")

long_data$Year <- seq(2001,2023,1)
colnames(long_data) <- c("Year", "Value")

# Plot
ggplot(data = long_data, aes(x = Year, y = as.numeric(Value),color="hotpink")) +
  geom_point() +
  geom_smooth()+
  labs(title = "Total Asylum Filings Over the Years",
       x = "Year",
       y = "Number of Filings") +
  theme_minimal()

# merge by year, each for year: one column for filing, one column for decisions, 
# use left_join(data1, data2)

```

